FROM rust:1.47
COPY ./iroha_macro /iroha_root/iroha_macro
COPY ./iroha_network /iroha_root/iroha_network
COPY ./iroha_logger /iroha_root/iroha_logger
COPY ./iroha /iroha_root/iroha
COPY ./Cargo.lock /iroha_root/iroha/Cargo.lock
WORKDIR /iroha_root/iroha
RUN cargo build --features "dex"
RUN cp ./config.json ./target/debug/config.json
CMD ["/iroha_root/iroha/target/debug/iroha"]
